### PR TITLE
Kham

### PR DESCRIPTION
**Pull request by cakimpei**
I found comments and suggestions for khanaa from @korakot in Colab. So I created new class Kham to be a representation for the word we spell and add \_\_repr__. Thank you @korakot. Thank you @wannaphong for sharing khanaa and wunsen too.

...

Also, I decided to refactor khanaa so that the code is easier to read and stores usable word data. SpellWord is left untouched. It will be deprecated and replaced by Kham. One of Kham attributes, 'form', is equal to SpellWord.spell_out which returns spelled form of the word.

Usage:

```python
spell = Kham(onset='ก', vowel='อา')
spell.form
# => 'กา'
```

Kham also has new methods.

- Kham.ipa() -> Return basic IPA pronunciation of the word. (It might need additional setting in kwargs to suit the needs).
- Kham.is_donee_end() -> Check if onset of the following word can be interpreted as this word's coda. (It will be True on ตา)
- Kham.is_donor_end() -> Check if coda of this word can be interpreted as the following word onset. (It will be True on ชาม)
- Kham.is_donor_start() -> Check if onset of this word can be interpreted as coda of the preceding word. (It will be True on กลม)

The last three methods might be useful if we want to place hyphen to disambiguate the words. For example, if we write ตา+กลม=ตากลม, the word can be interpreted as ตา-กลม or ตาก-ลม. But we can check for the word like ตา from is_donee_end(), that followed by the word like กลม from is_donor_start(), and put hyphen between them as ตา-กลม. Same as ชาม+กลม=ชามกลม which can also be interpreted as ชา-มก-ลม.

Usage example: Adding hyphen in transliteration ชเวปยีตา > ชเว-ปยีตา (a town in Myanmar).

New options in kwargs: split_true_cluster, split_false_cluster, split_leading_con, low_single_h_thoo

Hopefully Kham won't introduce new bugs. (It passes test cases. I also generated a million random inputs and preferences to make sure that Kham's result is not different from SpellWord's result). Speedwise, Kham is 2 times slower than SpellWord. (On my end, Kham takes around 20 seconds for 1,000,000 runs while SpellWord takes around 10 seconds, for the input 'เขียน').

Other details:

- Add Jattawaa tone for checked syllable such as ก๋ะ, กั๋ก, ค๋ะ, คั๋ก, ง๋ะ, งั๋ก as they're in Thai language textbooks.
- In all_tone(), now if the word can't have the particular tone, it will return that word with empty strings. (Before: ['กะ', 'กะ', 'ก้ะ', 'ก๊ะ', 'กะ'], Now: ['', 'กะ', 'ก้ะ', 'ก๊ะ', 'ก๋ะ']). This is not related to Kham.form which will still try to spell the word as -1.

### CODE REVIEW

**Comment by korakot** [comment]
Wow! Your work is amazing. Do you happen to study (or teach) at Chula? Hope we can work together on the database of Kham-syllable (with frequency from TNC or Google).

**Comment by cakimpei** [comment]
Thank you! I'm glad that this project might be useful for people other than myself.

I'm an alumni :) with major not related to CS or linguistics. But if I can be of any help, please let me know.

Database of Kham-syllable sounds interesting! I assume it's Kham from Khanaa? If you would like to, could you share about Khanaa's use case in this project? Honestly I can't think of Khanaa use case outside supporting transliteration project like Wunsen.

**Comment by korakot** [comment]
I see the syllable database as something fundamental to both
word-segmentation and speech recognition/synthesis.

Your newest features seem to touch on this direction. Your is_donee_end,
is_donor_start method is a big part. We can find statistics on how often
ตากลม or โล่งอก happens if we have the syllable database. We can answer
questions like what's the probability of each coda given a certain vowel.
Which form of อะ is more frequent, อัก or อะ? Or for the use case of
helping young learners, what are the most frequent 1-syllable words that
has a certain rhyme (or just coda). So we can help a teacher choose the
probable-to-be-found words instead of some rare words. And so on, and so
on... you get the idea.

Your work is already halfway there, I guess it may take you less than a
week to finish the database. I can be of help too, if you don't have much
time at the moment.

**Comment by cakimpei** [comment]
Not sure if it's what you have in mind, but I'm working on basic regex to split a syllable into parts (onset, vowel, coda etc). After I finish it, I'll try to apply this to word frequency list.

**Comment by cakimpei** [comment]
I'm not sure which word frequency list should be used, and I don't think I can find/access the ones you've mentioned. But I've finished regex. Please see #2

**Pull request merged**
